### ISSUE TITLE
Unicode decode error while trying to decode.

### ISSUE THREAD

**Issue by v3ss0n** [tinloaf/autocomplete-plus-python-jedi#1]
``` python
[21339:0404/075311:INFO:CONSOLE(64)] "Jedi.py Error: Traceback (most recent call last):
  File "/home/v3ss/.atom/packages/autocomplete-plus-python-jedi/lib/jedi-cmd.py", line 95, in <module>
    cmdline.run()
  File "/home/v3ss/.atom/packages/autocomplete-plus-python-jedi/lib/jedi-cmd.py", line 88, in run
    self._watch()
  File "/home/v3ss/.atom/packages/autocomplete-plus-python-jedi/lib/jedi-cmd.py", line 80, in _watch
    self._process_line(line)
  File "/home/v3ss/.atom/packages/autocomplete-plus-python-jedi/lib/jedi-cmd.py", line 48, in _process_line
    params = self._get_params(completion)
  File "/home/v3ss/.atom/packages/autocomplete-plus-python-jedi/lib/jedi-cmd.py", line 28, in _get_params
    param_defs = completion.params
  File "/home/v3ss/workspace/machine_learning/lib/python2.7/site-packages/jedi/evaluate/cache.py", line 39, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/v3ss/workspace/machine_learning/lib/python2.7/site-packages/jedi/api/classes.py", line 337, in params
", source: /home/v3ss/.atom/packages/autocomplete-plus-python-jedi/lib/jedi-provider.coffee (64)
[21339:0404/075311:INFO:CONSOLE(64)] "Jedi.py Error:     followed = self._follow_statements_imports()
  File "/home/v3ss/workspace/machine_learning/lib/python2.7/site-packages/jedi/evaluate/cache.py", line 39, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/v3ss/workspace/machine_learning/lib/python2.7/site-packages/jedi/api/classes.py", line 518, in _follow_statements_imports
    i._importer.module).follow(self._evaluator)
  File "/home/v3ss/workspace/machine_learning/lib/python2.7/site-packages/jedi/evaluate/imports.py", line 338, in follow
    scope, rest = self.follow_file_system()
  File "/home/v3ss/workspace/machine_learning/lib/python2.7/site-packages/jedi/evaluate/cache.py", line 39, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/v3ss/workspace/machine_learning/lib/python2.7/site-packages/jedi/evaluate/imports.py", line 365, in follow_file_system
    module, rest = self._follow_sys_path(sys_path_mod)
  File "/home/v3ss/workspace/machine_learning/lib/python2.7/site-packages/jedi/evaluate/imports.py", line 469, in _follow_sys_path
    return _load_module(path, source, sys_path=sys_path), rest
  File "/home/v3ss/workspace/machine_learning/lib/python2.7/site-packages/jedi/evaluate/imports.py", line 527, in _load_module
    return load(source) if cached is None else cached.module
  File "/home/v3ss/workspace/machine_learning/lib/python2.7/site-packages/jedi/evaluate/imports.py", line 522, in load
", source: /home/v3ss/.atom/packages/autocomplete-plus-python-jedi/lib/jedi-provider.coffee (64)
[21339:0404/075311:INFO:CONSOLE(64)] "Jedi.py Error:     p = fast.FastParser(common.source_to_unicode(source), p)
  File "/home/v3ss/workspace/machine_learning/lib/python2.7/site-packages/jedi/common.py", line 148, in source_to_unicode
    return unicode(source, detect_encoding(), 'replace')
LookupError: unknown encoding: iso-latin-1-unix
```

**Comment by tinloaf** [comment]
That is rather strange. This could even be a Jedi bug. Do you have non-UTF-8-encoded python files in your project, and if so, what are they encoded with?

**Comment by v3ss0n** [comment]
The file it tries to parse do not have

``` python
#!/usr/bin/python
# -*- coding: utf-8 -*-
```

Because of that?

**Comment by tinloaf** [comment]
Adding that line would probably hint Jedi to parse it as utf-8, yes. Could you try that?

Also, could you try

```
file /path/to/that/file
```

on the command line? That should tell you how that file is encoded...

**Comment by v3ss0n** [comment]
rechat.py: Python script, ASCII text executable

**Comment by tinloaf** [comment]
But that file does in fact contain non-ASCII characters? Then adding the coding: utf-8 header probably is your best chance. This hardly seems an issue with the plugin, rather an issue with Jedi, if at all. Do you know how to use Jedi from the command line? If you could verify that this does in fact produce the same error...

**Comment by v3ss0n** [comment]
i will look into it.

**Comment by v3ss0n** [comment]
Seems to be working fine after utf-8 headers added at the start.

**Comment by tinloaf** [comment]
This was a Jedi problem (or rather: a problem with the project, that was not caught by Jedi..), and there is a potential fix: https://github.com/davidhalter/jedi/pull/565

Closing this for now.
