### ISSUE TITLE
Failed to load the autocomplete-plus-python-jedi package

### ISSUE THREAD

**Issue by benmccormick** [tinloaf/autocomplete-plus-python-jedi#30]
I'm seeing the following issue when I try to load this plugin on Atom v1.0.0

**Atom Version**: 1.0.0
**System**: Mac OS X 10.10.3
**Thrown From**: [autocomplete-plus-python-jedi](https://github.com/tinloaf/autocomplete-plus-python-jedi) package, v0.3.6
### Stack Trace

Failed to load the autocomplete-plus-python-jedi package

```
At Cannot find module 'jquery'

Error: Cannot find module 'jquery'
    at Module._resolveFilename (module.js:328:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Object.<anonymous> (/Users/ben/.atom/packages/autocomplete-plus-python-jedi/lib/acp-python-jedi.coffee:6:7)
    at Object.<anonymous> (/Users/ben/.atom/packages/autocomplete-plus-python-jedi/lib/acp-python-jedi.coffee:67:4)
    at Module._compile (module.js:452:26)
    at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
    at Module.load (module.js:347:32)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".DS_Store",
      "*.pyc"
    ],
    "followSymlinks": true
  }
}
```
### Installed Packages

``` coffee
# User
autocomplete-plus-python-jedi, v0.3.6
cursor-history, v0.4.13
linter, v1.0.4
linter-eslint, v1.0.8
linter-jshint, v0.1.6
linter-less, v2.0.0
vim-mode, v0.54.0

# Dev
vim-mode, v0.15.0
```

**Comment by tinloaf** [comment]
Hi! I'm sorry to reply so late, but I had hoped that this problem would vanish on it's own: This plugin has long been abandoned in favor of https://github.com/sadovnychyi/autocomplete-python ..

The Atom folks wanted to somehow mark my plugin as deprecated, but have not done so yet, as it seems. So, please switch over to that other one!
